global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds.
  evaluation_interval: 30s # Evaluate rules every 30 seconds.
  external_labels:
    instance: "${YOUR_OPERATOR_NAME}" # replace this with your Operator name you want to be identified by, it helps us route alerts and metrics to your notification channels easily

remote_write:
  - url: http://testnet-metrics.chainbase.com:9090/api/v1/write

scrape_configs:
  - job_name: "chainbase-avs"
    metrics_path: /metrics
    static_configs:
      - targets: ["chainbase-node:8080"]